workflows:
  ios-release:
    name: iOS App Store Release
    max_build_duration: 60
    integrations:
      app_store_connect: CantApp
    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.cant.sportsapp
      flutter: stable
      xcode: latest
      groups:
        - Available to all workflows
    scripts:
      - name: Restore secret files
        script: |
          printf '%s' "$FIREBASE_OPTIONS" > lib/firebase_options.dart
          sed -i '' 's/MAPS_API_KEY_PLACEHOLDER/'"$MAPS_API_KEY_IOS"'/g' ios/Runner/AppDelegate.swift
      - name: Get Flutter packages
        script: flutter pub get
      - name: Set build number
        script: |
          BUILD_NUMBER=$(($(app-store-connect get-latest-testflight-build-number 6777126565) + 1))
          echo "New build number: $BUILD_NUMBER"
          cd $CM_BUILD_DIR
          agvtool new-version -all $BUILD_NUMBER
      - name: Set up code signing
        script: xcode-project use-profiles
      - name: Build iOS IPA
        script: |
          flutter build ipa --release \
            --export-options-plist=/Users/builder/export_options.plist
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
 