// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAgkYwi-j2Fb54go0octwBBH4lNn77pd6U',
    appId: '1:801298594312:web:b263f269d89c71198eafbd',
    messagingSenderId: '801298594312',
    projectId: 'sports-community-d6b15',
    authDomain: 'sports-community-d6b15.firebaseapp.com',
    databaseURL: 'https://sports-community-d6b15-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'sports-community-d6b15.firebasestorage.app',
    measurementId: 'G-S4CTG7CQ59',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBn_dr2wqtv4YgEqxusyFQ2yYYv06nX7c8',
    appId: '1:801298594312:android:dd9b2e68eba9f5d58eafbd',
    messagingSenderId: '801298594312',
    projectId: 'sports-community-d6b15',
    databaseURL: 'https://sports-community-d6b15-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'sports-community-d6b15.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB30EGDKs2JZu4Qw8kSfVMYe3wE4zXAemI',
    appId: '1:801298594312:ios:3e918e783d5144308eafbd',
    messagingSenderId: '801298594312',
    projectId: 'sports-community-d6b15',
    databaseURL: 'https://sports-community-d6b15-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'sports-community-d6b15.firebasestorage.app',
    iosBundleId: 'com.example.sportsCommunity',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB30EGDKs2JZu4Qw8kSfVMYe3wE4zXAemI',
    appId: '1:801298594312:ios:3e918e783d5144308eafbd',
    messagingSenderId: '801298594312',
    projectId: 'sports-community-d6b15',
    databaseURL: 'https://sports-community-d6b15-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'sports-community-d6b15.firebasestorage.app',
    iosBundleId: 'com.example.sportsCommunity',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAgkYwi-j2Fb54go0octwBBH4lNn77pd6U',
    appId: '1:801298594312:web:9170cc5e00fea4478eafbd',
    messagingSenderId: '801298594312',
    projectId: 'sports-community-d6b15',
    authDomain: 'sports-community-d6b15.firebaseapp.com',
    databaseURL: 'https://sports-community-d6b15-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'sports-community-d6b15.firebasestorage.app',
    measurementId: 'G-15SRFNRPYX',
  );
}
